public enum ItemType
{
    MetalScrap,
    Wiring,
    CoreFragment,
    RepairKit,
    MobilityPatch,
    SensorPatch,
    CircuitScrap,
    EnergyCell,
    SignalProcessor,
    ConduitComponents,
    StabilizerModule,
    PowerRegulator,
    PowerCoupler,
    TransitActuator,
    TransitCore,
    TransitControlModule
}
